export const Constant = {
  titleTemperature: "NHIỆT ĐỘ",
  titleDissolveOxy: "ĐỘ ẨM ĐẤT",
  redWarning: "Red warning",
  yellowWarning: "Yellow warning",
  titlepH: "ÁNH SÁNG",
  titleSalinity: "ĐỘ ẨM",
  temperatureHighHigh: 40,
  temperatureHigh: 35,
  temperatureLow: 20,
  temperatureLowLow: 18,
  dissolveOxyHighHigh:70,
  dissolveOxyHigh:60,
  dissolveOxyLow: 20,
  dissolveOxyLowLow: 25,
  pHHighHigh: 60,
  pHHigh: 55,
  pHLow: 10,
  pHLowLow: 7,
  salinityHighHigh: 70,
  salinityHigh: 60,
  salinityLow: 20,
  salinityLowLow: 15,

  timeSamplingData: 10000,
};
